traceTime function for performance debugging
garyb/purescript-debug pull request #30
Opened 2022-02-05 03:15 UTC by fsoikin

May I offer a contribution of the `traceTime` function, which is intended for performance debugging by surrounding suspicious blocks and measuring their run time.

We've been using this function quite successfully for a while, and I figured why not contribute to the library.

Works much like `trace` itself:

```purs
doSomething x y =
  x + (traceTime "cleverCalc" \_ -> cleverCalc y)
```

Prints out something like:

```
cleverCalc took 300ms
```

2022-02-06 18:48 UTC, garyb commented
Is `req` documented anywhere? I see that it works! Just curious as to whether it's "safe" to rely on it as I wasn't able to find much on it by googling (doesn't help that a lot of express related stuff comes up because `req` and `res` are common vars in there by convention)

2022-02-06 19:23 UTC, fsoikin commented
Oh, `req` is actually a locally defined thing, at the top of that file: https://github.com/garyb/purescript-debug/pull/30/files#diff-3e5cec0d814b798aed16805c96e2eccb76a37d7837d0d84120a40dbc3bd680b6R4

It's already used for another import, so I thought I'd take advantage here as well.

2022-02-06 19:26 UTC, fsoikin commented
I'm a bit confused with the `const` errors. Is the CI working with an older compiler?

2022-02-06 20:07 UTC, fsoikin commented
Oh, I see it is indeed using 0.14.0. Would you mind if I upgraded to 0.14.5?

2022-02-06 20:59 UTC, garyb commented
Oh! Haha. I see what happened now, when you open a `node` repl and type `req`, it auto-completes to `require` when you press enter too, so that's why I thought it was a thing there.

I'd actually rather switch the implementation of this to ES5 - although we are getting modules and stuff soon-ish, it's my preference that the only non-ES5 feature used in core/my libraries is the module stuff, as then it will work in environments that don't support >ES5 with only a bundling stage, and no need for babel or anything further.

2022-02-06 21:10 UTC, fsoikin commented
Sorry, I don't understand. Are you asking me to make a change?

2022-02-06 21:13 UTC, garyb commented
Yes please - I'd rather this be written as if it's still 1999, because unfortunately some environments still don't understand `const`, arrow functions, etc.

2022-02-06 21:35 UTC, fsoikin commented
Oh, you mean the JS syntax! Got it.

2022-02-06 21:42 UTC, fsoikin commented
Done.

* No arrow functions.
* No `let` or `const`.
* No string interpolation.
* Lines ending with semicolons.

I think that's all?

2022-02-10 23:09 UTC, garyb requested changes
Ah yeah, sorry the JS thing wasn't clear at first! 

I have one more question/suggestion, but other than that it looks great.

2022-02-10 23:09 UTC, garyb commented on src/Debug.js
> +    return (function() { return new Date(); });
I guess this works just now because `valueOf` for `Date` turns it into milliseconds? Maybe we should use `Date.now()` instead?

2022-02-11 01:16 UTC, fsoikin commented on src/Debug.js
> +    return (function() { return new Date(); });
Sure, that sounds reasonable. Done.

2022-05-01 20:28 UTC, garyb commented
I'm really sorry this dropped off my radar. Thanks!

2022-05-01 20:28 UTC, merged

2022-05-01 21:03 UTC, fsoikin commented
No worries at all! Thanks for accepting.